export default async function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  const SLACK_WEBHOOK = "https://hooks.slack.com/services/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";
  const { entries, stats, winner } = req.body;

  try {
    const today = new Date().toLocaleDateString("en-IN", {
      weekday: "long", day: "2-digit", month: "2-digit", year: "numeric",
      timeZone: "Asia/Kolkata"
    });

    const formatMins = (mins) => {
      if (mins === null || mins === undefined) return "—";
      if (mins < 60) return `${mins}m`;
      return `${Math.floor(mins / 60)}h ${mins % 60}m`;
    };

    const total = entries.length;
    const resolved = entries.filter(e => e.status === "Resolved").length;
    const pending = entries.filter(e => e.status === "Pending").length;
    const escalated = entries.filter(e => e.status === "Escalated").length;

    const issueCount = {};
    entries.forEach(e => { issueCount[e.issue] = (issueCount[e.issue] || 0) + 1; });
    const topIssue = Object.entries(issueCount).sort((a, b) => b[1] - a[1])[0];

    const allDiffs = entries.filter(e => e.diffMins).sort((a, b) => a.diffMins - b.diffMins);
    const fastest = allDiffs[0];
    const slowest = allDiffs[allDiffs.length - 1];

    const lines = [
      `📦 *EOD Performance Report — ${today}*`,
      ``,
      `📊 *Today's Summary*`,
      `• Total Issues: *${total}*  |  ✅ Resolved: *${resolved}*  |  ⏳ Pending: *${pending}*${escalated > 0 ? `  |  🔴 Escalated: *${escalated}*` : ""}`,
      ``,
      `👥 *Team Breakdown*`,
      ...stats.map(s =>
        `• *${s.person}* → ${s.total} issues | ${s.resolved} resolved | avg ${formatMins(s.avg)} | fastest ${formatMins(s.fastest)}${s.person === winner ? "  ⭐ *STAR OF THE DAY*" : ""}`
      ),
      ``,
      topIssue ? `🔥 *Top Issue Today:* ${topIssue[0]} (${topIssue[1]} cases)` : "",
      fastest ? `⚡ *Fastest Response:* ${fastest.respondedBy} — ${formatMins(fastest.diffMins)} (${fastest.sellerName})` : "",
      slowest && slowest.id !== fastest?.id ? `🐢 *Slowest Response:* ${slowest.respondedBy} — ${formatMins(slowest.diffMins)} (${slowest.sellerName})` : "",
      ``,
      `_Report auto-generated by Seller Response Tracker_`
    ].filter(Boolean);

    const reportText = lines.join("\n");

    const slackRes = await fetch(SLACK_WEBHOOK, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ text: reportText })
    });

    const slackBody = await slackRes.text();

    if (!slackRes.ok) {
      return res.status(500).json({ 
        error: `Slack error: ${slackRes.status} — ${slackBody}` 
      });
    }

    return res.status(200).json({ success: true, report: reportText });

  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
}
